Algoritmo "Saudacão"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 



Var
    curso: caractere
     nome: caractere
    idade: inteiro
     peso: real
   altura: real
   genero: caractere
   

Inicio

      escreva ( " Digite Seu Curso: " )
      leia (Curso)
      escreval ("")

      escreva ( " Digite Seu Nome: " )
      leia (nome)
      escreval ("")

      escreva ( " Digite Sua Idade: " )
      leia (idade)
      escreval ("")

      escreva ( " Digite Seu Peso: " )
      leia (peso)
      escreval ("")

      escreva ( " Digite Sua Altura: " )
      leia (altura)
      escreval ("")

      escreva ( " Digite Seu Gênero: " )
      leia (genero)
      escreval ("")

      escreva ( " Olá " ,nome ,  " === Seja Bem Vindo Ao Mundo Da Programação! === ")
      escreval ("")

Fimalgoritmo