Algoritmo "02_soma"

// Unimar - Universidade de Marilia
// Graduacao: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algoritimos e Logica de Programacao]
// Professor   : Ronie Tokumo
// Aluno : Luiz Leandro de Oliveira

Var

   n1,n2, soma: inteiro

Inicio

   escreval ( " ==== Programa de Soma ==== " )
   escreval ("")

   escreva ( " Lance o Primeiro Valor: " )
   leia (n1)
   escreval("")

   escreva ( " Lance o Segundo Valor: " )
   leia (n2)
   escreval ("")

   soma <- n1 + n2

   escreval ( " Resultado: " , soma )
   escreval ("")

   escreval ( " +++ Soma Executada Com Sucesso +++ " )
   escreval ("")
Fimalgoritmo
