Algoritmo "03_somando_calculando_media"

Unimar - Universidade de Marília
// Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
Disciplina   : [Algoritmos e Lógica de Programação]
// Professor   : Ronie Tokumo
// Aluno :   Luiz Leandro de Oliveira

Var

   n1,n2, soma: inteiro
   media: real

Inicio

   Escreval ( " *** Programa de Soma e Média *** " )
   escreval ("")

   escreva ( " Lance o Primeiro Valor: " )
   leia (n1)
   escreval ("")

   escreva ( " Lance o Segundo Valor: " )
   leia (n2)
   escreval("")

   soma <- n1+n2
   media <- soma / 2

   escreval ( " O Resultado da Soma é: " , soma )
   escreval ("")

   escreval ( " A Media dos Lançamentos é: " , média )
   escreval ("")

   escreval ( " ||| Soma e Média Realizadas com Exito ||| " )

Fimalgoritmo
