Algoritmo "04_multiplicacao"

// Unimar - Universidade de Marilia
// Graduacao: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algoritmos e Logica de Programacao]
// Professor   : Ronie Tokumo
// Aluno : Luiz Leandro de Oliveira 

Var

   num1, num2, resultado: real

Inicio

      escreval ( " == Programa de Operação Matemática: Multiplicação == " )
      escreval("")
      
      escreva( " Faça o Lançamento do Primeiro Número: " )
      leia (num1)
      escreval("")
      
      escreva ( " Por Qual Número Gostaria de Multiplicar? : " )
      leia (num2)
      escreval("")
      
      resultado <- num1 * num2
      
      escreval ( " O Resultado da Multiplicação é : " , resultado )
      escreval ("")
      
      escreval( " === Multiplicação Efetuada Com Sucesso === ")
      escreval ("")

      Fimalgoritmo
