Algoritmo "05_subtracao"

// Unimar - Universidade de Marilia
// Graduacao: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algoritmos e Logica de Programacao]
// Professor   : Ronie Tokumo
// Aluno :  Luiz Leandro de Oliveira

Var

   num1, num2, resultado: real

Inicio

      escreval ( " == Programa de Operação Matemática: Subtração == " )
      escreval("")
      
      escreva ( " Faça o Lançamento do Primeiro Número : " )
      leia (num1)
      escreval("")
      
      escreva ( " Faça o Lançamento do Segundo Número : ")
      leia (num2)
      escreval("")
      
      resultado <- num1 - num2
      
      escreval ( " Resultado da Operação : " , resultado )
      escreval ("")
      
      escreval ( " === Operação de Subtração Realizada === " )

Fimalgoritmo
