Algoritmo "11_contagem_1_a_10"

// Unimar - Universidade de Marília
// Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algorítimos e Lógica de Programação]
// Professor   : Ronie Tokumo
// Aluno: Luiz Leandro de Oliveira

Var

   i:inteiro

Inicio

   escreval ( " === Execução de Contagem de 01 Até 10 === " )
   escreval("")

   para i de 01 ate 10 faca
      escreva ( " Contando... " , i )
      escreval("")

   fimpara
   escreval("")

   escreval ( " === Contagem De 01 Até 10 Finalizada === " )
   escreval("")


Fimalgoritmo
