Algoritmo "14_conversao_celsius_fahrenheit"

// Unimar - Universidade de Marília
// Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algorítimos e Lógica de Programação]
// Professor   : Ronie Tokumo
// Aluno   : Luiz Leandro de Oliveira

Var

      celsius :real
   fahrenheit :real

Inicio

     escreval( "==== Converção de Celsius em Fahrenheit ====" )
     escreval("")
     
     escreval("Digite a temperatura em Celsius")
     leia (celsius)
     escreval("")

     fahrenheit <- (celsius * 9 /5) +32
     
     escreval (" A temperatura fahrenheit é : " , fahrenheit:0:2, "°f" )
     escreval("")
     
     escreval (" #### Conversão Executada #### ")
     
     

Fimalgoritmo
