Algoritmo "19_contador_negativo"

  // Unimar - Universidade de Marília
  // Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
  // Disciplina   : [Algorítimos e Lógica de Programação]
  // Professor   : Ronie Tokumo
  // Aluno   : Luiz Leandro de Oliveira

Var

   comeco:inteiro
      fim:inteiro
        i:inteiro

Inicio

     escreva ( " Digite o Valor Inicial: " )
     leia (comeco)
     escreval("")
     
     escreva ( " Digite o Valor Final (Negativo) : " )
     leia (fim)
     escreval("")
     
     para i de comeco ate fim passo -1 faca
     escreval ( " Contador: " ,i )
     fimpara
     

Fimalgoritmo
