Algoritmo "20_verifica_numero_10_20"

  // Unimar - Universidade de Marília
  // Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
  // Disciplina   : [Algorítimos e Lógica de Programação]
  // Professor   : Ronie Tokumo
  // Aluno   : Luiz Leandro de Oliveira

Var

   numero:inteiro

Inicio

      escreval ( " Digite Um Número: " )
      leia (numero)
      escreval("")
      
      se (numero >=10) e (numero <=20) entao
      escreval ( " O Número Esta Entre o 10 e 20. " )
      senao
      escreval ( " O Número NÃO Esta Entre o 10 e o 20. " )
      fimse
      

Fimalgoritmo
