Algoritmo "22_calcular_idade_atual"

  // Unimar - Universidade de Marília
  // Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
  // Disciplina   : [Algorítimos e Lógica de Programação]
  // Professor   : Ronie Tokumo
  // Aluno   : Luiz Leandro de Oliveira

Var

   anoNascimento:inteiro
   anoAtual     :inteiro
   idade        :inteiro

Inicio

      escreval ( " Digite Ano de Nascimento: " )
      leia(anoNascimento)
      
      escreval ( " Digite o Ano Atual: " )
      leia (anoAtual)
      
      idade <- AnoAtual - anoNascimento
      
      escreva (" A Idade Atual é De :" , idade, " Anos ." )
      

Fimalgoritmo
