Algoritmo "contagemDe1Ate10"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 



Var

   i:inteiro

Inicio

   escreval ( " === Execução de Contagem de 01 Até 10 === " )
   escreval("")

   para i de 01 ate 10 faca
      escreva ( " Contando... " , i )
      escreval("")

   fimpara
   escreval("")

   escreval ( " === Contagem De 01 Até 10 Finalizada === " )
   escreval("")


Fimalgoritmo