Algoritmo "dobro_triplo"

// Unimar - Universidade de Marilia
// Graduacao: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algoritmos e Logica de Programacao]
// Professor   : Ronie Tokumo

Var

   numero, dobro, triplo : real

Inicio

      escreval ( " === Programa de Calculo do Dobro e Triplo === " )
      escreval("")
      
      escreva ( " Digite um Número : " )
      leia(numero)
      escreval("")
      
      dobro <- numero * 2
      triplo <- numero * 3
      
      escreval ( " Número Lançado : " , numero )
      escreval ( " Dobro : " , dobro )
      escreval ( " Triplo : " , triplo )
      escreval("")
      
      escreval ( " === Processamento Realizado === " )

Fimalgoritmo