Algoritmo "parOuImpar"

Var

    numero:inteiro

Inicio
      escreval ( " === Revelação de Número Par ou Impar === " )
      escreval("")
      escreval ( " === Por Favor Digite Um Número === " )
      leia (numero)
      escreval("")
      se ( numero mod 2 = 0 ) entao
      escreval ( " Este Numero é Par ")
      
      senao
      escreval ( " Este Numero é Impar " )
      
      fimse
      


Fimalgoritmo