Algoritmo "Saudação"

// Unimar - Universidade de Marília
//// Graduacao: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algoritmos e Logica de Programacao]
// Professor   : Ronie Tokumo

Var
   curso: caractere
   nome: caractere
   idade: inteiro
   peso: real
   altura: real
   genero: caractere


Inicio

   escreva ( " Digite Seu Curso: " )
   leia (Curso)
   escreval ("")

   escreva ( " Digite Seu Nome: " )
   leia (nome)
   escreval ("")

   escreva ( " Digite Sua Idade: " )
   leia (idade)
   escreval ("")

   escreva ( " Digite Seu Peso: " )
   leia (peso)
   escreval ("")

   escreva ( " Digite Sua Altura: " )
   leia (altura)
   escreval ("")

   escreva ( " Digite Seu Genero: " )
   leia (genero)
   escreval ("")

   escreva ( " Ola " , nome ,  " === Seja Bem Vindo(a) Ao Mundo Da Programacao! === ")
   escreval ("")

Fimalgoritmo
