Algoritmo "somando_calculando_media"

 Unimar - Universidade de Marilia
// Graduacao: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algoritmos e Logica de Programacao]
// Professor   : Ronie Tokumo

Var

   n1,n2, soma: inteiro
   media: real

Inicio

   Escreval ( " *** Programa de Soma e Media *** " )
   escreval ("")

   escreva ( " Lance o Primeiro Valor: " )
   leia (n1)
   escreval ("")

   escreva ( " Lance o Segundo Valor: " )
   leia (n2)
   escreval("")

   soma <- n1+n2
   media <- soma / 2

   escreval ( " O Resultado da Soma é: " , soma )
   escreval ("")

   escreval ( " A Media dos Lançamentos é: " , media )
   escreval ("")

   escreval ( " ||| Soma e Media Realizadas com Exito ||| " )

Fimalgoritmo
