Algoritmo "somando E fazendo A média"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

   n1,n2, soma: inteiro
        media: real

Inicio

       Escreval ( " *** Programa de Soma e Média *** " )
       escreval ("")
       
       escreva ( " Lance o Primeiro Valor: " )
       leia (n1)
       escreval ("")
       
       escreva ( " Lance o Segundo Valor: " )
       leia (n2)
       escreval("")
       
       soma <- n1+n2
       media <- soma / 2

       escreval ( " O Resultado da Soma é: " , soma )
       escreval ("")

       escreval ( " A Média dos Lançamentos é: " , media )
       escreval ("")
       
       escreval ( " ||| Soma e Média Realizadas com Exito ||| " )

Fimalgoritmo