Algoritmo "soma"

// Unimar - Universidade de Marília
// Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algorítimos e Lógica de Programação]
// Professor   : Ronie Tokumo

Var

   n1,n2, soma: inteiro

Inicio

   escreval ( " ==== Programa de Soma ==== " )
   escreval ("")

   escreva ( " Lance o Primeiro Valor: " )
   leia (n1)
   escreval("")

   escreva ( " Lance o Segundo Valor: " )
   leia (n2)
   escreval ("")

   soma <- n1 + n2

   escreval ( " Resultado: " , soma )
   escreval ("")

   escreval ( " +++ Soma Executada Com Sucesso +++ " )
   escreval ("")
Fimalgoritmo