Algoritmo "todasAsTabuadas"

// Unimar - Universidade de Marília
// Graduação: Engenharia de Software - EAD Semipresencial MOD-1 [2026]
// Disciplina   : [Algorítimos e Lógica de Programação]
// Professor   : Ronie Tokumo

Var

   numero: inteiro
   i: inteiro
   resultado: inteiro

Inicio

   escreval ( " => Aqui Estão Todas as Tabuadas de 01 a 10 <= ")
   escreval("")

   para numero de 01 ate 10 faca
      escreval ( "  XXX Tabuada do Número " , numero ,  " XXX " )
      escreva("")
      escreval("")

      para i de 01 ate 10 faca
         resultado <- numero x i
         escreva("")

         escreval ( numero, "x" , i , "=" , resultado )


      fimpara
   fimpara

   escreval("")
   escreval ( " === Fim das Tabuadas === " )
   escreval ("")







Fimalgoritmo